# Generated by Django 5.2.5 on 2025-08-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('tenant', 'Арендатор'), ('landlord', 'Арендодатель'), ('administrator', 'Администратор')], max_length=20),
        ),
    ]
