# Generated by Django 5.2.5 on 2025-08-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('tenant', 'Mieter'), ('landlord', 'Vermieter')], max_length=20),
        ),
    ]
