# Generated by Django 5.2.5 on 2025-08-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='housing_type',
            field=models.CharField(choices=[('apartment', 'Wohnung'), ('house', 'Haus'), ('studio', 'Studio'), ('room', 'Zimmer')], max_length=20),
        ),
    ]
