# Generated by Django 5.2.5 on 2025-08-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_alter_listing_housing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cancellation_deadline_days',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
